---
# Write a Task to update and updgrade apt packages

- name: 'apt package maintenance'
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: 'Update and Upgrade apt packages'
      apt:
        update_cache: true
        upgrade: yes
        state: latest

...
