---

- name: 'apt package maintenance'
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: 'Update apt packages'
      apt:
        update_cache: true

    - name: 'Upgrade apt packages'
      apt:
        upgrade: yes
        state: latest

...
